// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtwh9qS0F4mwdrMKZKEoZxNh4yeg_DpWU',
    appId: '1:434336914712:web:9d87a4d14c567fc36cd26d',
    messagingSenderId: '434336914712',
    projectId: 'vump-platform-f86af',
    authDomain: 'vump-platform-f86af.firebaseapp.com',
    storageBucket: 'vump-platform-f86af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbtliU8Vv9TQXtTJBcyBpLDRu4eGmJyv0',
    appId: '1:434336914712:android:354d893c347c13916cd26d',
    messagingSenderId: '434336914712',
    projectId: 'vump-platform-f86af',
    storageBucket: 'vump-platform-f86af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDipvD18WEAmYvDXDtdmJAA7f6nQFHj1FE',
    appId: '1:434336914712:ios:44df9e701043e8136cd26d',
    messagingSenderId: '434336914712',
    projectId: 'vump-platform-f86af',
    storageBucket: 'vump-platform-f86af.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDipvD18WEAmYvDXDtdmJAA7f6nQFHj1FE',
    appId: '1:434336914712:ios:44df9e701043e8136cd26d',
    messagingSenderId: '434336914712',
    projectId: 'vump-platform-f86af',
    storageBucket: 'vump-platform-f86af.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtwh9qS0F4mwdrMKZKEoZxNh4yeg_DpWU',
    appId: '1:434336914712:web:53f01902b48ed3446cd26d',
    messagingSenderId: '434336914712',
    projectId: 'vump-platform-f86af',
    authDomain: 'vump-platform-f86af.firebaseapp.com',
    storageBucket: 'vump-platform-f86af.firebasestorage.app',
  );
}
